modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/SilentChaos512/Equipment-Tooltips/issues"
displayURL="https://minecraft.curseforge.com/projects/equipment-tooltips"
logoFile="logo.png"
credits=""
authors="SilentChaos512"

[[mods]]
    modId="equipmenttooltips"
    version="${file.jarVersion}"
    displayName="Equipment Tooltips"
    description='''
    Stat icons for tools, weapons, and armor.
    '''

[[dependencies.equipmenttooltips]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.equipmenttooltips]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="CLIENT"
